[build-system]
requires = ["maturin>=1.14"]
build-backend = "maturin"

[project]
name = "bit-counter"
readme = "README.md"
dynamic = ["version", "summary", "description", "description_content_type"]
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]

[dependency-groups]
dev = [
    "maturin>=1.14.0",
    "numpy>=1.21.6",
    "pytest>=7.4.4",
]

[tool.maturin.generate-ci.github]
trusted-publishing = true
publishing-environment = "release"
